### ISSUE TITLE
Getting started example still uses bower

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xtermjs.org#48]
:scream:

**Comment by pro-src** [comment]
@Tyriar I think the best way to solve this and other issues related to the site becoming outdated/out-of-sync is to reuse the markdown from xterm.js repository's README.md. We can do so by exporting parts of it to `_includes/chunk-of-markdown.md`. There's not a lot of work to be done since were already cloning the repo to generate docs. Thus, I propose we simply add some comments to the README.MD to mark what should exported.

```html
<!-- export _includes/real-world-use-cases.md -->
Anything here... *_markdown_* or this could be in an HTML file.
<!-- endexport -->
```

The following is exactly the same as above but without an inline HTML code block or IOW without the backticks.

Anything here... *_markdown_* or this could be in an HTML file.


As you can see the comments above are invisible...
We would just need to add something like the following to the gulpfile:

```js
import path from 'path';
import fs from 'fs-extra';

const markdown = // Scan a directory for .md files or read a specific file's data
const exported = extract(markdown, 'export', 'endexport');

const fileOps = Object.keys(exported).map(async (relativePath) => {
  const absolutePath = path.resolve(__dirname, relativePath);
  await fs.writeFile(absolutePath, exported[relativePath], 'utf-8');
});

Promise.all(fileOps).then(() => console.log('Files have been exported'));

// Supports nesting comments and appending
function extract(data, start, end) {
  const comment = /<!--(.*?)-->/;
  const opening = /^\s*(\S+)\s+(\S+)\s*$/;
  const remaining = [];
  const results = {};

  let current;
  while ((current = comment.exec(data)) !== null) {
    const [ directive, id ] = current[1].match(opening) || [ current ];
    if (directive === start) {
      remaining.push({ id, index: comment.lastIndex });
    }
    else if (directive.trim() === end) {
      const last = remaining.pop();
      if (last !== undefined) {
        results[last.id] = (results[last.id] || '') +
          data.slice(last.index, current.index);
      }
    }
  }

  if (remaining.length > 0) {
    throw new Error('Missing "${end}" for "${remaining[0].id}"');
  }

  return results;
}
```

The only restrictions is that there cannot be spaces in the filename. Minor improvements might be to add a checks to ensure that the path is relative, the destination directory already exists, renaming variables, etc..

I don't see any drawbacks at this time for adding this. See `_includes/xtermjs-description.md` in this repo which is essentially the product of having done this manually.

**Comment by pro-src** [comment]
The way I've suggested solving this is related to but in no way dependent upon
https://github.com/github/markup/issues/346 and https://github.com/github/markup/issues/1159

And the response: https://github.com/github/markup/issues/172#issuecomment-33241601

**Comment by Tyriar** [comment]
@pro-src this is probably a little overkill for the getting started, I think it's changed like twice in the last 2 years.

**Comment by pro-src** [comment]
Yea, but I was able to make it smaller and improve the regex. :thumbs:

Unduplify all the things! Lol

**Comment by pro-src** [comment]
@Tyriar here's it is. I quite like the way it turned out but totally agree with you that it's overkill. :smile: 

```js
// Copyright (c) 2018, The xterm.js Authors
const path = require('path');
const fs = require('fs-extra');

const markdown = fs.readFileSync(`./_xterm.js/README.md`, 'utf-8');
const chunks = extractChunks(markdown);

Promise.all(Object.keys(chunks).map(async (filename) => {
  const absPath = path.join(__dirname, '_includes', filename);
  await fs.writeFile(absPath, chunks[filename], 'utf-8');
}));

function extractChunks(data) {
  const comments = /<!-- *(begin|end)(?: +([^\0:?*"<>\\\/|]+?))? *-->\s*/gm;
  const remaining = [];
  const chunks = {};


  let match;
  while ((match = comments.exec(data)) !== null) {
    const [line, directive, filename] = match;

    if (directive === 'begin') {
      remaining.push({ filename, begin: comments.lastIndex });
      continue;
    }

    if (directive === 'end') {
      if (remaining.length < 1) {
        throw new Error('Missing "begin <filename>" for "end" at line:'
          + data.slice(0, match.index).split('\n').length);
      }
      const { begin, filename: id } = remaining.pop();
      chunks[id] = data.slice(begin, match.index);
    }
  }

  for (const { begin, filename: id } of remaining) {
    throw new Error(`Missing "end" for "begin ${id}" at line:`
      + data.slice(0, begin).split('\n').length);
  }

  return chunks;
}
```

**Comment by pro-src** [comment]
@Tyriar The :scream: emoji warrants a custom solution. Lol

**Comment by Tyriar** [comment]
Adding too much custom tooling could lead to it being overly fragile is my main concern, plus it adds ugly comments to the README :smile:
